prophet_baseline:
  seasonality_mode: "multiplicative"
  daily_seasonality: true
  yearly_seasonality: true
  weekly_seasonality: true
  monthly_seasonality: true
  changepoint_range: 0.95
  changepoint_prior_scale: 0.2
  fourier_order: 5
  horizon: 90
  future_days: 30

lstm:
  time_step: 60
  epochs: 300
  batch_size: 32
  learning_rate: 0.004236738510183372
  layers: 1
  units: 128
  dropout: 0.2937143644669184
  patience: 25
  test_size: 0.25

BiLSTM_model:
  layers: 1
  units: 128
  dropout: 0.474381420780048
  learning_rate: 0.005563285496088541
  batch_size: 32
  epochs: 300
  time_step: 60
  patience: 25
  test_size: 0.25

future_feature_engineering:
  forecast_horizon: 30
  rolling_signal_window: 252
  lag_inventory: 3
  rolling_window: 30

  prophet_params:
    seasonality_mode: "multiplicative"
    daily_seasonality: true
    weekly_seasonality: true
    yearly_seasonality: true
    changepoint_prior_scale: 0.2
    changepoint_range: 0.95
    monthly_fourier_order: 5

  garch_params:
    vol: "GARCH"
    p: 1
    q: 1
    dist: "ged"
