prophet_baseline:
  seasonality_mode: "multiplicative"
  daily_seasonality: true
  yearly_seasonality: true
  weekly_seasonality: true
  monthly_seasonality: true
  changepoint_range: 0.95
  changepoint_prior_scale: 0.2
  fourier_order: 5
  horizon: 90
  future_days: 30

lstm:
  time_step: 60
  epochs: 300
  batch_size: 32
  learning_rate: 0.0018847896888368458
  layers: 1
  units: 128
  dropout: 0.2107204924359533
  patience: 25
  test_size: 0.25


garch:
  p: 1
  q: 1
  dist: "ged"
