artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  yahoo_finance:
    ticker: "NG=F"
    start_date: "2009-01-01"
    end_date: "2025-05-28"
    data_file: artifacts/data_ingestion/yahoo_data.csv
  eia_api:
    api_key: ${EIA_API_KEY}
    start_date: "2010-01-01"
    end_date: "2025-05-28"
    data_file: artifacts/data_ingestion/eia_inventory.csv
  hdd_data:
    year_start: 2010
    base_url: "https://ftp.cpc.ncep.noaa.gov/htdocs/degree_days/weighted/daily_data"
    local_raw_path: artifacts/data_ingestion/hdd_data.txt
    processed_file: artifacts/data_ingestion/hdd_data.csv

prepare_data:
  root_dir: artifacts/prepare_data
  processed_data_path: artifacts/prepare_data/processed_data.csv

prophet_baseline:
  root_dir: artifacts/prophet_baseline
  model_file: artifacts/prophet_baseline/model.pkl
  forecast_file: artifacts/prophet_baseline/forecast.csv
  forecast_plot: artifacts/prophet_baseline/forecast_plot.png
  residual_plot: artifacts/prophet_baseline/residuals_plot.png
  component_plot: artifacts/prophet_baseline/prophet_components.png
  metrics_file: artifacts/prophet_baseline/prophet_metrics.json

lstm_model:
  root_dir: artifacts/lstm_model
  processed_data_path: artifacts/prepare_data/processed_data.csv
  model_path: artifacts/lstm_model/lstm_model.h5
  scaler_path: artifacts/lstm_model/scaler.pkl
  history_plot: artifacts/lstm_model/history.png
  prediction_plot: artifacts/lstm_model/prediction.png
  metrics_file: artifacts/lstm_model/metrics.json

bilstm_model:
  root_dir: artifacts/bilstm_model
  processed_data_path: artifacts/prepare_data/processed_data.csv
  model_path: artifacts/bilstm_model/bilstm_model.h5
  history_plot: artifacts/bilstm_model/history.png
  prediction_plot: artifacts/bilstm_model/prediction.png
  metrics_file: artifacts/bilstm_model/metrics.json
  scaler_path: artifacts/bilstm_model/scaler.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  lstm_metrics_path: artifacts/lstm_model/metrics.json
  bilstm_model_metrics_path: artifacts/bilstm_model/metrics.json 
  prophet_metrics_path: artifacts/prophet_baseline/prophet_metrics.json
  evaluation_report: artifacts/model_evaluation/evaluation_report.json
  evaluation_plot: artifacts/model_evaluation/model_comparison.png

future_feature_engineering:
  root_dir: artifacts/future_feature_engineering
  processed_data_path: artifacts/prepare_data/processed_data.csv
  output_path: artifacts/future_feature_engineering/future_features.csv

forecast:
  root_dir: artifacts/forecast
  forecast_results_path: artifacts/forecast/forecast_results.csv

logging:
  log_file: artifacts/logs/project.log
  level: INFO
